"""aipt.backends.mock.replay -- replay captured real traffic as Mock turns.

DESIGN.md 4.5/5 (B3): once ``aipt.backends.public_ai.recorder`` (B2) has
captured a real request/response exchange in the same schema
``aipt.backends.mock.records.ScenarioRecord`` uses, the Mock backend should be
able to play it back without talking to a real model again.

**Byte pattern only, not timing** (DESIGN.md 4.5 "확정된 설계 결정" row 3,
and B3's own line in the table): a captured exchange's *answer text* is
worth reproducing on the wire because it is what actually produced the
byte counts and packet pattern the capture is evidence of. Its *latency*
is not reproduced -- delay stays a separate, explicit knob
(``inference_delay_ms``, the same parameter the byte-size-sweep mode
already used) so replay stays simple and so a "replay this capture but
faster/slower" run is just a different delay argument, not a different
record.

So this module does the minimum: load a capture file (any object shaped
like ``{"turns": [{"question": ..., "answer": ...}, ...]}`` -- the exact
shape a recorder or a hand-built record already produces), and rebuild a
:class:`~aipt.backends.mock.records.ScenarioRecord` whose answers are
truncated to placeholder bytes of *the same length* as the captured answer.
The question text is kept verbatim (it drives request-size logic the same
way a live record's question does); only the answer -- the part actually
generated by a slow, non-deterministic model -- is reduced to a
byte-count-preserving placeholder, because replaying byte-identical
*content* would be misleading (it did not come from this run) while
byte-identical *size* is exactly the thing being reproduced.
"""

from __future__ import annotations

import json
from pathlib import Path

from aipt.backends.mock.records import ScenarioRecord, Turn

# Filler byte used for placeholder answers, matching the '"x" * n' padding
# convention already used by aipt.backends.mock.records.byte_size_scenario
# and the original tcp_congestion server's body dummy bytes.
_FILLER = "x"


def _placeholder(byte_len: int) -> str:
    """*byte_len* bytes of ASCII filler -- 1 byte == 1 char for the filler
    character chosen, so len(str.encode()) == byte_len exactly."""
    return _FILLER * max(0, byte_len)


def _capture_turn_of(raw: object, i: int) -> Turn:
    if not isinstance(raw, dict):
        raise ValueError(f"captured turn {i} is not an object: {type(raw).__name__}")
    question = raw.get("question")
    answer = raw.get("answer")
    if not isinstance(question, str):
        raise ValueError(f"captured turn {i} needs a string 'question' field")
    if not isinstance(answer, str):
        raise ValueError(f"captured turn {i} needs a string 'answer' field")
    # Byte pattern only: keep the question (drives request size / history
    # growth like any other record question), replace the answer with a
    # same-length placeholder so wire bytes match without replaying content
    # that did not come from this run.
    return Turn(question=question, answer=_placeholder(len(answer.encode())))


def from_capture_doc(doc: dict, *, name: str = "replay") -> ScenarioRecord:
    """Build a byte-pattern-only :class:`ScenarioRecord` from an in-memory
    capture document (already parsed JSON, same schema as a Q&A record file)."""
    turns = [_capture_turn_of(t, i) for i, t in enumerate(doc.get("turns") or [])]
    system_prompt = doc.get("system_prompt", "")
    return ScenarioRecord(
        name=doc.get("name", name),
        system_prompt=_placeholder(len(system_prompt.encode())) if system_prompt else "",
        description=f"replay of {doc.get('name', name)} (bytes only, no timing)",
        turns=turns,
    )


def from_capture_file(path: str | Path) -> ScenarioRecord:
    """Load a capture JSON file (as produced by
    ``aipt.backends.public_ai.recorder``, or hand-authored in the same
    schema) and rebuild it as a byte-pattern-only replay
    :class:`ScenarioRecord`.
    """
    p = Path(path)
    doc = json.loads(p.read_text())
    return from_capture_doc(doc, name=p.stem)


def from_public_ai_record_doc(doc: dict, *, name: str = "replay") -> ScenarioRecord:
    """Build a byte-pattern-only :class:`ScenarioRecord` from a
    ``aipt.backends.public_ai.recorder.RecordWriter`` document -- the
    ``data/public_ai_records/<exec_id>.json`` schema (DESIGN.md 4.7.1),
    which is *not* quite the plain ``{"turns": [{"question", "answer"}]}``
    shape :func:`from_capture_doc` expects: turns carry ``response_text``
    (the real model's answer text, already recorded per DESIGN.md B2) and
    a wealth of other request/response detail this replay never needs.

    Same byte-pattern-only contract as :func:`from_capture_doc`: keep the
    real question (it drove real request-size behaviour and should drive
    the same request size again), replace the real answer text with a
    same-length placeholder (replaying byte-identical *content* from a
    call that is not this run would be misleading; byte-identical *size*
    is exactly what a "was this run's TCP behaviour representative"
    experiment needs).
    """
    turns = []
    for i, raw in enumerate(doc.get("turns") or []):
        if not isinstance(raw, dict):
            raise ValueError(f"record turn {i} is not an object: {type(raw).__name__}")
        question = raw.get("question")
        if not isinstance(question, str):
            raise ValueError(f"record turn {i} needs a string 'question' field")
        answer = raw.get("response_text") or ""
        turns.append(Turn(question=question, answer=_placeholder(len(answer.encode()))))
    system_prompt = doc.get("system", "") or ""
    return ScenarioRecord(
        name=doc.get("name", name),
        system_prompt=_placeholder(len(system_prompt.encode())) if system_prompt else "",
        description=f"replay of public_ai record {name} (bytes only, no timing)",
        turns=turns,
    )
