stateDiagram-v2
    START_OR_GLOBAL --> RRC: 5.3.1.1
    START_OR_GLOBAL --> AND: 5.3.1.1
    RRC_IDLE --> CONNECTED: 5.3.3.1
    RRC_IDLE --> RRC: 5.3.3.1
    START_OR_GLOBAL --> CONNECTED: 5.3.3.4
    START_OR_GLOBAL --> RRC: 5.3.3.4
    START_OR_GLOBAL --> FAILURE: 5.3.3.4
    START_OR_GLOBAL --> FAILURE: 5.3.3.7
    MUSIM --> FAILURE: 5.3.5.3
    START_OR_GLOBAL --> CONCERNED: 5.3.5.5.9
    START_OR_GLOBAL --> AND: 5.3.5.11
    START_OR_GLOBAL --> FAILURE: 5.3.7.5
    START_OR_GLOBAL --> RRC: 5.3.8.1
    START_OR_GLOBAL --> RRC: 5.3.8.3
    START_OR_GLOBAL --> INACTIVE: 5.3.8.3
    START_OR_GLOBAL --> RRC_IDLE: 5.3.11
    START_OR_GLOBAL --> RRC: 5.3.11
    START_OR_GLOBAL --> IDLE: 5.3.11
    START_OR_GLOBAL --> FOR: 5.3.13.2
    START_OR_GLOBAL --> CONNECTED: 5.3.13.4
    START_OR_GLOBAL --> MEASUREMENT: 5.3.13.4
    START_OR_GLOBAL --> RRC: 5.3.13.4
    START_OR_GLOBAL --> AND: 5.3.13.4
    START_OR_GLOBAL --> FAILURE: 5.3.13.4
    START_OR_GLOBAL --> FAILURE: 5.3.13.5
    START_OR_GLOBAL --> FAILURE: 5.3.13.6
    START_OR_GLOBAL --> FAILURE: 5.3.13.11
    START_OR_GLOBAL --> RRC: 5.3.15.2
    START_OR_GLOBAL --> FREQUENCY: 5.5.2.1
    START_OR_GLOBAL --> MEASUREMENT: 5.5.2.2
    START_OR_GLOBAL --> MEASUREMENT: 5.5.2.3
    START_OR_GLOBAL --> MEASUREMENT: 5.5.2.4
    START_OR_GLOBAL --> MEASUREMENT: 5.5.2.5
    START_OR_GLOBAL --> MEASUREMENT: 5.5.2.6
    START_OR_GLOBAL --> MEASUREMENT: 5.5.2.7
    START_OR_GLOBAL --> MEASUREMENT: 5.5.2.8
    START_OR_GLOBAL --> MEASUREMENT: 5.5.4.1
    START_OR_GLOBAL --> CONCERNED: 5.5.4.1
    RRC_IDLE --> MEASUREMENT: 5.5.7.1
    START_OR_GLOBAL --> FREQUENCY: 5.7.4.3
    START_OR_GLOBAL --> FAILURE: 5.7.10.3
    RRC_IDLE --> CONNECTED: 5.8.9.8.1
    RRC_IDLE --> RRC: 5.8.9.8.1
    RRC_IDLE --> FAILURE: 5.8.9.10.2
    START_OR_GLOBAL --> FAILURE: 5.8.9.10.3
    START_OR_GLOBAL --> MEASUREMENT: 5.8.10.2.3
    START_OR_GLOBAL --> MEASUREMENT: 5.8.10.2.4
    START_OR_GLOBAL --> MEASUREMENT: 5.8.10.2.5
    START_OR_GLOBAL --> MEASUREMENT: 5.8.10.2.6
    START_OR_GLOBAL --> MEASUREMENT: 5.8.10.2.7
    START_OR_GLOBAL --> MEASUREMENT: 5.8.10.2.8
    START_OR_GLOBAL --> CONCERNED: 5.8.10.4.1
    START_OR_GLOBAL --> RRC: 6.2.1
    RRC_IDLE --> FREQUENCY: 6.2.2
    RRC_IDLE --> RRC: 6.2.2
    RRC_IDLE --> IDLE: 6.2.2
    RRC_IDLE --> CAUSE: 6.2.2
    RRC_IDLE --> FOR: 6.2.2
    RRC_IDLE --> INACTIVE: 6.2.2
    RRC_IDLE --> AND: 6.2.2
    RRC_IDLE --> PROCEDURES: 6.2.2
    RRC_IDLE --> FAILURE: 6.2.2
    RRC_IDLE --> FREQUENCY: 6.3.1
    RRC_IDLE --> FREQUENCY: 6.3.2
    RRC_IDLE --> CAUSE: 6.3.2
    RRC_IDLE --> AND: 6.3.2
    START_OR_GLOBAL --> FREQUENCY: 6.3.3
    START_OR_GLOBAL --> RRC_IDLE: 6.3.4
    START_OR_GLOBAL --> FREQUENCY: 6.3.4
    START_OR_GLOBAL --> RRC: 6.3.4
    START_OR_GLOBAL --> IDLE: 6.3.4
    START_OR_GLOBAL --> FOR: 6.3.5
    RRC --> FOR: 6.3.6
    START_OR_GLOBAL --> FOR: 6.4
    RRC_IDLE --> FOR: 6.6.2
    RRC --> RRC_IDLE: 7.1.1
    RRC --> IDLE: 7.1.1
    RRC --> PROCEDURES: 7.1.1
    RRC_IDLE --> FAILURE: 7.4
    START_OR_GLOBAL --> FREQUENCY: 11.2.2
    RRC --> CAUSE: # 12 Processing
    RRC --> PROCEDURES: # 12 Processing
    RRC --> FAILURE: # 12 Processing
