stateDiagram-v2
    RRC_IDLE --> RRC_CONNECTED: 5.3.3.1
    RRC_INACTIVE --> RRC_CONNECTED: 5.3.3.4
    RRC_CONNECTED --> RRC_INACTIVE: 5.3.8.3
    RRC_CONNECTED --> RRC_IDLE: 5.3.11
    RRC_INACTIVE --> RRC_CONNECTED: 5.3.13.4
    UNKNOWN --> RRC_CONNECTED: 5.8.9.8.1
    RRC_IDLE --> RRC_IDLE: 6.3.4
    RRC_IDLE --> RRC_IDLE: 7.1.1
