stateDiagram-v2
    START_OR_UNKNOWN --> IDLE: 5.3.3.6
    START_OR_UNKNOWN --> RRC: 5.3.3.6
    START_OR_UNKNOWN --> CONNECTED: 5.3.3.8
    START_OR_UNKNOWN --> RRC: 5.3.3.8
    START_OR_UNKNOWN --> IDLE: 5.3.5.5.2
    START_OR_UNKNOWN --> RRC: 5.3.5.5.2
    START_OR_UNKNOWN --> IDLE: 5.3.7.5
    START_OR_UNKNOWN --> RRC: 5.3.7.5
    START_OR_UNKNOWN --> IDLE: 5.3.7.6
    START_OR_UNKNOWN --> RRC: 5.3.7.6
    START_OR_UNKNOWN --> IDLE: 5.3.7.7
    START_OR_UNKNOWN --> RRC: 5.3.7.7
    START_OR_UNKNOWN --> IDLE: 5.3.8.3
    START_OR_UNKNOWN --> RRC: 5.3.8.3
    START_OR_UNKNOWN --> IDLE: 5.3.8.5
    START_OR_UNKNOWN --> CONNECTED: 5.3.8.5
    START_OR_UNKNOWN --> RRC: 5.3.8.5
    START_OR_UNKNOWN --> IDLE: 5.3.8.6
    START_OR_UNKNOWN --> RRC: 5.3.8.6
    START_OR_UNKNOWN --> IDLE: 5.3.9.2
    START_OR_UNKNOWN --> RRC: 5.3.9.2
    START_OR_UNKNOWN --> IDLE: 5.3.10.3
    START_OR_UNKNOWN --> RRC: 5.3.10.3
    START_OR_UNKNOWN --> IDLE: 5.3.11
    START_OR_UNKNOWN --> RRC: 5.3.11
    START_OR_UNKNOWN --> INACTIVE: 5.3.11
    START_OR_UNKNOWN --> IDLE: 5.3.13.6
    START_OR_UNKNOWN --> RRC: 5.3.13.6
    RRC --> IDLE: 5.3.13.8
    START_OR_UNKNOWN --> IDLE: 5.3.13.11
    START_OR_UNKNOWN --> RRC: 5.3.13.11
    START_OR_UNKNOWN --> IDLE: 5.3.13.12
    START_OR_UNKNOWN --> RRC: 5.3.13.12
    START_OR_UNKNOWN --> IDLE: 5.4.3.5
    START_OR_UNKNOWN --> RRC: 5.4.3.5
    RRC --> IDLE: 5.7.8.1
    RRC --> CONNECTED: 5.7.8.1
    RRC --> INACTIVE: 5.7.8.1
    START_OR_UNKNOWN --> CONNECTED: 5.7.9.2
    START_OR_UNKNOWN --> RRC: 5.7.9.2
    RRC --> IDLE: 5.8.9.8.2
    RRC --> INACTIVE: 5.8.9.8.2
    RRC --> CONNECTED: 5.9.4.2
    START_OR_UNKNOWN --> IDLE: 7.1.1
    START_OR_UNKNOWN --> CONNECTED: 7.1.1
    START_OR_UNKNOWN --> RRC: 7.1.1
